/**
 * Generates src/content/icons.ts from the installed `lucide-static` package.
 *
 * The division marks are not drawn by hand and not transcribed by hand — they
 * are extracted from a real, versioned icon family at build time. That is the
 * whole point: one family means one stroke weight, one corner radius and one
 * optical size by construction, instead of six drawings that have to be
 * policed into agreeing with each other.
 *
 * Run: npm run icons
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const pkg = require('lucide-static/package.json');
const ICONS_DIR = new URL('../node_modules/lucide-static/icons/', import.meta.url);

/** division id -> lucide icon name */
const MAP = {
  projectDevelopment: 'building-2',
  realEstateInvestment: 'trending-up',
  transactionManagement: 'handshake',
  constructionManagement: 'hard-hat',
  assetManagement: 'vault',
  advisoryManagement: 'compass',
};

const body = (name) => {
  const raw = readFileSync(new URL(`${name}.svg`, ICONS_DIR), 'utf8');
  const m = raw.match(/<svg[^>]*>([\s\S]*?)<\/svg>/);
  if (!m) throw new Error(`could not parse ${name}.svg`);
  return m[1]
    .split('\n')
    .map((l) => l.trim())
    .filter(Boolean)
    .join('\n    ');
};

const entries = Object.entries(MAP)
  .map(([id, name]) => `  // lucide/${name}\n  ${id}: \`\n    ${body(name)}\`,`)
  .join('\n');

writeFileSync(
  new URL('../src/content/icons.ts', import.meta.url),
  `// GENERATED by scripts/build-icons.mjs — do not edit.
// Source: lucide-static v${pkg.version} (ISC). Re-run \`npm run icons\` to update.
//
// Lucide is stroke-based, which is why it is the right family here: the marks
// inherit the site's own line weight rather than sitting on it as filled
// shapes. Authored at 24 units — see ICON_VIEWBOX in divisions.ts.

export const ICONS: Record<string, string> = {
${entries}
};
`,
);

console.log(`wrote src/content/icons.ts from lucide-static v${pkg.version}`);
for (const [id, name] of Object.entries(MAP)) console.log(`  ${id} -> lucide/${name}`);
